wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1730043475
    t:
      1:
      - 1
      - 30
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 30
      - 41
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.8.19
      5: 0.17.9
      8:
      - 2
      - 5
      13: linux-x86_64
